### ISSUE TITLE
Structure repository + create placeholders

### ISSUE THREAD

**Issue by vgkienzler** [lean-office-apps/tickets-management-web#4]
1. Create placeholders and/or templates for README.rst, LICENSE.md, CHANGLOG.md, CONTRIBUTING.md
2. Move all the django apps files and folders under a single folder "project"
3. Create the structure for the following django apps:
    * Tickets
    * Logging
    * Workflows

**Comment by vgkienzler** [comment]
'Logging' isn't possible so changing app name to 'monitoring'.

**Comment by umarkayondo** [comment]
Concerning issue number 3;
When a django app is created, it should be in the same folder as the manage.py file. We should then think about moving all custom logic which is not a Django app to one folder that lies at the root of the main app.
For example something like this;
```
project
           core
           tickets
           logging
           workflows
           custom
                    utilities
                    otherfolder1
                    otherfolder2
          manage.py
```
In the above example core is the root application, tickets, logging & workflows are other applications, then custom is a folder containing anything that we can think of.

**Comment by vgkienzler** [comment]
@umarkayondo thanks for your post, we will do that later once the "custom" files and folders are more stable and we get more clarity on what file/folder does what and what would be the impact of moving it around.

So right now we have this:

```
ticket-management-web
        docs
        nginx
        project
            app (to be replace by one of our apps)
            authentication
            core
            media (this should probably be moved)
            monitoring (logging was not possible)
            staticfiles (should be moved too)
            tickets
            workflows
```
